/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INT.interfaces;

/**
 *
 * @author ChewbakaS
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_BTN_CompteRendu = new javax.swing.JButton();
        jButton_BTN_Visiteur = new javax.swing.JButton();
        jButton_BTN_Praticien = new javax.swing.JButton();
        jButton_BTN_Medicament = new javax.swing.JButton();
        jButton_BTN_Quitter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INT/images/GSB.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton_BTN_CompteRendu.setText("Comptes-Rendus");
        jButton_BTN_CompteRendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BTN_CompteRenduActionPerformed(evt);
            }
        });

        jButton_BTN_Visiteur.setText("Visiteurs");

        jButton_BTN_Praticien.setText("Praticiens");
        jButton_BTN_Praticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BTN_PraticienActionPerformed(evt);
            }
        });

        jButton_BTN_Medicament.setText("Médicaments");

        jButton_BTN_Quitter.setText("Quitter");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Gestion des comptes rendus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_BTN_CompteRendu, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jButton_BTN_Visiteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_BTN_Praticien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_BTN_Medicament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton_BTN_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_BTN_CompteRendu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_BTN_Visiteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_BTN_Praticien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_BTN_Medicament)
                .addGap(18, 18, 18)
                .addComponent(jButton_BTN_Quitter)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BTN_CompteRenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BTN_CompteRenduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BTN_CompteRenduActionPerformed

    private void jButton_BTN_PraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BTN_PraticienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BTN_PraticienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BTN_CompteRendu;
    private javax.swing.JButton jButton_BTN_Medicament;
    private javax.swing.JButton jButton_BTN_Praticien;
    private javax.swing.JButton jButton_BTN_Quitter;
    private javax.swing.JButton jButton_BTN_Visiteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
